### ISSUE TITLE
Release v0.1

### ISSUE THREAD

**Issue by Tectu** [Tectu/malloy#26]
I'd like to start working towards the initial `0.1` release.
This issue should serve as a discussion for figuring out what should happen before the `0.1` release.

@0x00002a any inputs from your side?

# Features & Fixes
- Required
  - #17
  - #19
- Optional
  - #24
  - #25

**Comment by 0x00002a** [comment]
Great! I'm hoping to pr `feat-custom-requests` at some point today (hopefully soon), just gotta fix some build issues and finish the writeup. Thats gonna need some review and possibly lots of tweaking and I suggest we sort that out before since its a pretty major change (at least for websockets). If we wanna go ahead with 0.1 without it though that might be a good idea too since it is such a major change and probably has some new bugs. 

I'm also planning on setting up a [conan](https://conan.io) package for this, at least hosted on a free artifcatory instance (I could try getting it into the conan central repo but I've never done that before). 

For the mingw, I think we should get the CI to build with mingw, that way we would at least have warning that it got broke before you tried to compile. But thats gonna be a real PITA I think, might have to do some copy-pasting of the workflow since I don't think I can do it with the matrix.

**Comment by Tectu** [comment]
I agree. Let's wait for your PR then on #17 then.

**Comment by Tectu** [comment]
@0x00002a anything else you deem important enough to put into `v0.1`?

**Comment by 0x00002a** [comment]
Nothing off the top of my head, so no :p.

**Comment by Tectu** [comment]
Well, in that case we can close this issue :p
