### ISSUE TITLE
Add TLS support for websockets

### ISSUE THREAD

**Issue by Tectu** [Tectu/malloy#36]
Currently, we have implemented TLS support for HTTP client & server. However, WebSocket support is currently plain only.

@0x00002a did you by any chance already start working on this when you restructured the websocket connections?

**Comment by 0x00002a** [comment]
I didn't start working on it exactly, although I can have a go at doing this (I've never done TLS websockets before so might take a bit :p), but I did implement it with TLS in mind (thats why `stream` exsits, to wrap a possible TLS version of it)

**Comment by 0x00002a** [comment]
@Tectu I think quite a clean way to do this would be letting the user pass in a uri which was parsed for either `ws://` or `wss://` but since the API already has http/https versions do you think it would be better to have a `make_secure_websocket_connection` instead? Also `make_websocket_connection` is quite a mouthful, I'm not sure if it can really be shortend without losing clarity but `make_secure_websocket_connection` is too long imo. `ws_connect` and `wss_connect` could work?
